### ISSUE TITLE
Error: Json parse error : illegal value

### ISSUE THREAD

**Issue by viniciuspatzer** [CheshireCaat/puppeteer-with-fingerprints#11]
Everything was working fine, and suddenly overnight all my projects using puppeteer-with-fingerprints it's throwing the following error:

Error: Json parse error : illegal value
at SocketService. (C:\Users\vinic\Desktop\Test Project\node_modules\bas-remote-node\src\index.js:45:26)
at SocketService.emit (node:events:513:28)
at C:\Users\vinic\Desktop\Test Project\node_modules\bas-remote-node\src\services\socket.js:41:16
at Array.forEach ()
at C:\Users\vinic\Desktop\Test Project\node_modules\bas-remote-node\src\services\socket.js:39:14
at Timeout._onTimeout (C:\Users\vinic\Desktop\Test Project\node_modules\chnl\dist\channel.cjs.js:2:4848)
at listOnTimeout (node:internal/timers:569:17)
at process.processTimers (node:internal/timers:512:7)

**Comment by viniciuspatzer** [comment]
I've already tried deleting the data folder, it doesn't help. I'm using the lastest version.
