### ISSUE TITLE
Browser download broken

### ISSUE THREAD

**Issue by Alfonsoe96** [CheshireCaat/puppeteer-with-fingerprints#45]
The browser is downloading - this may take some time.

TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at SocketService.close (C:\Users\Administrator\Documents\node_modules\bas-remote-node\src\services\socket.js:101:14)
    at BasRemoteClient.close (C:\Users\Administrator\Documents\node_modules\bas-remote-node\src\index.js:291:20)
    at C:\Users\Administrator\Documents\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:38:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
TypeError: Cannot read properties of undefined (reading 'removeAllListeners')
    at SocketService.close (C:\Users\Administrator\Documents\node_modules\bas-remote-node\src\services\socket.js:101:14)
    at BasRemoteClient.close (C:\Users\Administrator\Documents\node_modules\bas-remote-node\src\index.js:291:20)
    at C:\Users\Administrator\Documents\node_modules\browser-with-fingerprints\src\plugin\connector\index.js:38:20
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  level: 'warn',
  [Symbol(level)]: 'warn'
}

TypeError: Cannot read properties of undefined (reading 'kill')
    at C:\Users\Administrator\Documents\node_modules\bas-remote-node\src\services\engine.js:152:23
    at <anonymous>
TypeError: Cannot read properties of undefined (reading 'kill')
    at C:\Users\Administrator\Documents\node_modules\bas-remote-node\src\services\engine.js:152:23
    at <anonymous> {
  level: 'warn',
  [Symbol(level)]: 'warn'
}

**Comment by CheshireCaat** [comment]
Should be fixed already, check it out.
