### ISSUE TITLE
Unable to update lock

### ISSUE THREAD

**Issue by Daednoise** [CheshireCaat/puppeteer-with-fingerprints#74]
Receiving this error using the example code provided in the README:

```
D:\code\fwgs_pup\node_modules\proper-lockfile\lib\lockfile.js:213
        onCompromised: (err) => { throw err; },
                                  ^

Error: Unable to update lock within the stale threshold
    at D:\code\fwgs_pup\node_modules\proper-lockfile\lib\lockfile.js:136:25
    at newFs.<computed> [as stat] (D:\code\fwgs_pup\node_modules\proper-lockfile\lib\adapter.js:20:13)
    at Timeout._onTimeout (D:\code\fwgs_pup\node_modules\proper-lockfile\lib\lockfile.js:114:20)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ECOMPROMISED'
}

Node.js v21.6.1
```

**Comment by btakakho** [comment]
Same error
Node.js v20.11.0
