### ISSUE TITLE
TypeError: Cannot create proxy with a non-object as target or handler

### ISSUE THREAD

**Issue by omar6995** [CheshireCaat/puppeteer-with-fingerprints#79]
Hi, I was using the library with no problem but recenthly when launching a new browser. I  get this error : 
`puppeteer-with-fingerprints\node_modules\puppeteer-with-fingerprints\src\utils.js:26
    browser.createIncognitoBrowserContext = new Proxy(browser.createIncognitoBrowserContext, {
                                            ^

TypeError: Cannot create proxy with a non-object as target or handler
    at exports.bindHooks (C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\puppeteer-with-fingerprints\src\utils.js:26:45)
    at PuppeteerFingerprintPlugin.configure (C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\puppeteer-with-fingerprints\src\index.js:39:7)
    at #run (C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\browser-with-fingerprints\src\plugin\index.js:92:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppeteerFingerprintPlugin.launch (C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\browser-with-fingerprints\src\plugin\index.js:112:12)
    at async PuppeteerFingerprintPlugin.launch (C:\laragon\www\Prospkt\nodejs\puppeteer-with-fingerprints\node_modules\puppeteer-with-fingerprints\src\index.js:9:12)      
    at async Browser.init (file:///C:/laragon/www/Prospkt/nodejs/puppeteer-with-fingerprints/browser.js:38:20)
    at async file:///C:/laragon/www/Prospkt/nodejs/puppeteer-with-fingerprints/app.js:19:1`

Here is my code main.js 

`const browser = new Browser();
await browser.init(false);`

in the browser.js class : 

`async init(headless = true) {
    const fingerprint = await plugin.fetch(key, { tags: ['Microsoft Windows', 'Chrome'] });
    const proxy = this.getNextProxy();
    plugin.useProxy(proxy, {
      // Change browser timezone according to proxy:
      changeTimezone: true,
      changeBrowserLanguage: true,
      changeGeolocation: true,
      changeWebRTC: true,
      detectExternalIP: true
    });
    this.browser = await plugin.useFingerprint(fingerprint).launch({ headless: headless });
  }`

**Comment by omar6995** [comment]
I'm not sure, but I'd say that the [FingerprintSwitcher](https://fingerprints.bablosoft.com/) API changed the type of data returned causing this issue ?

**Comment by CheshireCaat** [comment]
In version 22.0.0 puppeteer has [renamed](https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.0.0) the createIncognitoBrowserContext method, you need to update the plugin, while it is not there you must downgrade the version of puppeteer/puppeteer-core to the previous ones.

**Comment by omar6995** [comment]
Thanks, moving to puppeteer 21.11.0 seems to fix the issue

**Comment by CheshireCaat** [comment]
@omar6995 I made a fix and released a new version, with it you can use the latest puppeteer versions.
