### ISSUE TITLE
Can't u‌se metamask extension

### ISSUE THREAD

**Issue by SCP120** [CheshireCaat/puppeteer-with-fingerprints#84]
Hi. when i adding metamask extension to the args . in plugin.launch it gave me this error

>  ProtocolError: Runtime.callFunctionOn timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
    at Callback.<instance_members_initializer> (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\common\CallbackRegistry.ts:117:12)
    at new Callback (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\common\CallbackRegistry.ts:122:3)
    at CallbackRegistry.create (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\common\CallbackRegistry.ts:27:22)
    at Connection._rawSend (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\cdp\Connection.ts:120:22)
    at CdpCDPSession.send (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\cdp\CDPSession.ts:95:29)
    at ExecutionContext.#evaluate (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\cdp\ExecutionContext.ts:282:44)
    at ExecutionContext.evaluate (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\cdp\ExecutionContext.ts:157:32)
    at IsolatedWorld.evaluate (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\cdp\IsolatedWorld.ts:143:26)
    at CdpFrame.evaluate (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\api\Frame.ts:478:35)
    at CdpFrame.<anonymous> (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\util\decorators.ts:61:21)
    at CdpPage.evaluate (D:\abct-monorepo\node_modules\puppeteer\node_modules\puppeteer-core\src\api\Page.ts:2208:35)
    at waitForResize (D:\abct-monorepo\node_modules\puppeteer-with-fingerprints\src\utils.js:110:38)
    at exports.setViewport (D:\abct-monorepo\node_modules\puppeteer-with-fingerprints\src\utils.js:77:83)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at D:\abct-monorepo\node_modules\browser-with-fingerprints\src\plugin\config.js:25:19

my code:
`

         pluginFingerprint.useFingerprint(fingerprint);

        // pluginFingerprint.useProfile("D:/abct-monorepo/data/profiles/lUUD2k9g", {
        //     // Don't load fingerprint from profile folder:
          

        // });
        pluginFingerprint.useBrowserVersion('default');
        const browser = await pluginFingerprint.launch({
            ignoreDefaultArgs: ["--disable-extensions"],
            headless: false,
            
            args: [--disable-extensions-except=${metamaskPath} , --load-extension=${metamaskPath}]
        });
`

**Comment by CheshireCaat** [comment]
The **metamask** extension uses special protection, not allowing external scripts to work; in the case of puppeteer/playwright and analogues, JS injections are often used, which is why errors most likely occur. Unfortunately, this is more a problem of frameworks than of plugins - you can try using **BAS**, the extension should work correctly there.
